# Generated by Django 5.0.6 on 2024-06-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='modelo',
            field=models.CharField(max_length=30, verbose_name='Modelo da Bike'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='preco',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Loja')),
                ('cnpj', models.CharField(max_length=25)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('produtos', models.ManyToManyField(to='bikes.bike')),
            ],
        ),
    ]
