# Generated by Django 5.0.6 on 2024-06-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_bike_descricao_alter_bike_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=30)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.loja', verbose_name='Loja atuante')),
            ],
        ),
    ]
