# Generated by Django 5.0.6 on 2024-06-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_alter_vendedor_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.loja', verbose_name='loja_vendedor'),
        ),
    ]
