# Generated by Django 5.0.6 on 2024-08-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_bikeinventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BikeInventory',
        ),
    ]
